[tool.black]
line-length = 100
target-version = ['py312']

[tool.pylint."messages control"]
ignore = ["setup.py", "__init__.py"]
disable = "all"
enable = [
  "empty-docstring",
  "missing-class-docstring",
  "missing-function-docstring",
  "missing-module-docstring"
]

[tool.isort]
profile = "black"

[tool.pyright]
reportMissingTypeArgument = true
strictListInference = true
reportPrivateImportUsage = false