name: CLI Tool Sanity Check

on:
  push:
    branches:
      - main
      - 'dev-*'

jobs:
  cli-sanity:
    needs: static
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Package in Editable Mode
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Validate CLI Does Not Crash
        run: |
          # Run the CLI in single execution mode
          OUTPUT=$(local-operator --hosting test --model test-model exec "print hello world")
          
          # Check if the output contains "hello world"
          if ! echo "$OUTPUT" | grep -i "I have printed 'Hello World' to the console" > /dev/null; then
            echo "Expected output containing 'I have printed 'Hello World' to the console', but got:"
            echo "$OUTPUT"
            exit 1
          fi